export const teamdata = {
  S01: {
    'College Name': 'Reva University (RU), Bangalore, Karnataka',
    'Team Name': 'TechFortune23',
    'Team Leader': 'Debarun Ghosh',
    Category: 'Social Innovation',
    Participants: ['Ayan Kumar', 'Pooja Mallik'],
  },
  S02: {
    'College Name': 'National Institute of Technology Karnataka (NITK), Surathkal',
    'Team Name': 'Dev-Int',
    'Team Leader': 'Mardav Gandhi',
    Category: 'Social Innovation',
    Participants: ['Fahim Ahmed', 'Hriday Mehta'],
  },
  S03: {
    'College Name': 'Shri Madhwa Vadiraja Institute of Technology and Management (SMVITM), Shankarapura, Karnataka',
    'Team Name': 'Runtime Terrors',
    'Team Leader': 'Prathvi Rao',
    Category: 'Social Innovation',
    Participants: ['Arathi Kini', 'Aaron Sharon'],
  },
  S04: {
    'College Name': 'Kristu Jayanthi college bangalore',
    'Team Name': 'The Coding Collective',
    'Team Leader': 'Samuel Shine',
    Category: 'Social Innovation',
    Participants: ['Shruti Das', 'Aadar Shrestha'],
  },
  S05: {
    'College Name': 'GM Institute of Technology (GMIT), Davangere, karnataka',
    'Team Name': 'RED',
    'Team Leader': 'Shravan Hajare',
    Category: 'Social Innovation',
    Participants: ['Vanamali Sedimbi', 'Shivashankar M N'],
  },
  S06: {
    'College Name': 'GM Institute of Technology (GMIT), Davangere, karnataka',
    'Team Name': 'Voltage Vikings',
    'Team Leader': 'Sagar Patil',
    Category: 'Social Innovation',
    Participants: ['Varun S', 'Tushar B R'],
  },
  S07: {
    'College Name': 'St. Joseph Engineering College, Vamanjoor',
    'Team Name': 'Bytenamics',
    'Team Leader': 'Anish Shobith P S',
    Category: 'Social Innovation',
    Participants: ['Jessica James Fernandes', 'Abhinav Sudesh'],
  },
  S08: {
    'College Name': 'St. Joseph Engineering College, Vamanjoor',
    'Team Name': 'Innovative thinkers',
    'Team Leader': 'Jeevan K',
    Category: 'Social Innovation',
    Participants: ['Dominic Peter', 'Hemachandra'],
  },
  S09: {
    'College Name': 'St. Joseph Engineering College, Vamanjoor',
    'Team Name': 'Necta',
    'Team Leader': 'Vineeth Shenoy',
    Category: 'Social Innovation',
    Participants: ['Reevan Coelho', 'Mohammed Rabil'],
  },
  S10: {
    'College Name': 'Shri Madhwa Vadiraja Institute of Technology and Management (SMVITM), Shankarapura, Karnataka',
    'Team Name': 'Bit by Bit',
    'Team Leader': 'Rathan R Nayak',
    Category: 'Social Innovation',
    Participants: ['Vijayakumara Biradar', 'Pradwin Sherigar'],
  },
  S11: {
    'College Name': 'Manipal Institute of Technology (MIT), Manipal',
    'Team Name': 'Lumos',
    'Team Leader': 'Harry Raj',
    Category: 'Social Innovation',
    Participants: ['Tanishq Singh', 'Triya Roy'],
  },
  S12: {
    'College Name': 'St. Joseph Engineering College, Mangalore, Karnataka',
    'Team Name': 'The Byte Brigade',
    'Team Leader': 'A Sanjana B Bhat',
    Category: 'Social Innovation',
    Participants: ['Vaishnavi Bharadwaj', 'Anujna K'],
  },
  S13: {
    'College Name': 'St. Joseph Engineering College, Mangalore, Karnataka',
    'Team Name': 'Syntax Error',
    'Team Leader': 'Chaithanya K',
    Category: 'Social Innovation',
    Participants: ['Charishma Shivani', 'Ashburn Simon Noronha'],
  },
  S14: {
    'College Name': 'Sahyadri College of Engineering & Management (SCEM), Mangaluru',
    'Team Name': 'Sushrutha',
    'Team Leader': 'Bhat Nishanth Ganesh',
    Category: 'Social Innovation',
    Participants: ['Maroor Chethan Pai', 'Anudeep K K'],
  },
  H01: {
    'College Name': 'St Joseph Engineering College',
    'Team Name': 'SHERLOCKES',
    'Team Leader': 'Vijay A S',
    Category: 'Healthcare',
    Participants: ['Brian Menenzes', 'Bhavish J'],
  },
  H02: {
    'College Name': 'St Joseph Engineering College (SJEC), Mangaluru',
    'Team Name': 'PPA',
    'Team Leader': 'Pravin Kumar',
    Category: 'Healthcare',
    Participants: ['Pragnya Nagure', 'Avinash Muralidharan'],
  },
  H03: {
    'College Name': 'St Joseph Engineering College (SJEC), Mangaluru',
    'Team Name': 'The Crusaders',
    'Team Leader': 'Joyal Menezes',
    Category: 'Healthcare',
    Participants: [],
  },
  H04: {
    'College Name': 'NMAM Institute of Technology (NMAMIT), Nitte',
    'Team Name': 'Team kryptonite',
    'Team Leader': 'Navaneeth Kulal',
    Category: 'Healthcare',
    Participants: ['Dayanidhi R'],
  },
  H05: {
    'College Name': 'St Joseph Engineering College (SJEC), Mangaluru',
    'Team Name': 'Synergy',
    'Team Leader': 'Tina Benita Rego',
    Category: 'Healthcare',
    Participants: ['Sharanya S Shetty', 'Vanesha Relitsa Cutinho'],
  },
  H06: {
    'College Name': 'Mangalore Institute of Technology & Engineering (MITE), Mangaluru, Karnataka',
    'Team Name': 'Code Red',
    'Team Leader': 'Varun Raj',
    Category: 'Healthcare',
    Participants: ['Mahesh Narasimha', 'Hithesh Suvarna'],
  },
  H07: {
    'College Name': 'Shri Madhwa Vadiraja Institute of Technology and Management (SMVITM), Shankarapura, Karnataka',
    'Team Name': 'Sweet pills',
    'Team Leader': 'Chandana B',
    Category: 'Healthcare',
    Participants: ['Shrutha Bhat', 'Shridhar S'],
  },
  H08: {
    'College Name': "Alva's Institute of Engineering and Technology, Karnataka",
    'Team Name': 'Bro code',
    'Team Leader': 'Shwetha R Sharma',
    Category: 'Healthcare',
    Participants: ['B Sai Shreya', 'Sahana G S'],
  },
  H09: {
    'College Name': 'St Joseph Engineering College (SJEC), Mangaluru',
    'Team Name': '630601-U0V54DO1',
    'Team Leader': 'Jeevan Kumar',
    Category: 'Healthcare',
    Participants: ['Souraj Rai', 'Rahul J'],
  },
  H10: {
    'College Name': 'Bearys institute of technology',
    'Team Name': 'Tech Pirate',
    'Team Leader': 'Mohammed Ajmal Husainnaikar',
    Category: 'Healthcare',
    Participants: ['Arfaz Ahmed'],
  },
  H11: {
    'College Name': 'St Joseph Engineering College',
    'Team Name': 'Tesseract',
    'Team Leader': 'Adith K V',
    Category: 'Healthcare',
    Participants: ['Samrudh A U', 'D Sathvik Pai'],
  },
  H12: {
    'College Name': 'St.aloysius college,mangalore',
    'Team Name': 'MedVault',
    'Team Leader': 'Nathan Sequeira',
    Category: 'Healthcare',
    Participants: ['Biru Hirkur', 'Royson Robert Fernandes'],
  },
  H13: {
    'College Name': 'St Joseph Engineering College (SJEC), Mangaluru',
    'Team Name': 'NEON',
    'Team Leader': 'Tanisha Shetty',
    Category: 'Healthcare',
    Participants: ['Rachan Karkera', 'Nihaal YK'],
  },
  H14: {
    'College Name': 'St Joseph Engineering College (SJEC), Mangaluru',
    'Team Name': 'falcons',
    'Team Leader': 'Rinette Veronica',
    Category: 'Healthcare',
    Participants: ['Rencita Monteiro', 'Riya D Almeida'],
  },
  H15: {
    'College Name': 'St Joseph Engineering College (SJEC), Mangaluru',
    'Team Name': '630601-U5ND789C',
    'Team Leader': 'Sharon Menezes',
    Category: 'Healthcare',
    Participants: ['Shane Priyanka', 'Chaitanya'],
  },
  F01: {
    'College Name': 'St Joseph Engineering College (SJEC), Mangaluru',
    'Team Name': 'Shawarma',
    'Team Leader': 'Muhammad Saheed',
    Category: 'Finance',
    Participants: ['Shelton Agera'],
  },
  F02: {
    'College Name': 'St Joseph Engineering College (SJEC), Mangaluru',
    'Team Name': 'Ham',
    'Team Leader': 'Abraham',
    Category: 'Finance',
    Participants: ['Shane Noronha', 'Avin Francis'],
  },
  F03: {
    'College Name': 'St Joseph Engineering College',
    'Team Name': 'PrintChange',
    'Team Leader': 'Shaun Furtado',
    Category: 'Finance',
    Participants: ['Shawn Monteiro'],
  },
  F04: {
    'College Name': 'NMAM Institute of Technology (NMAMIT), Nitte',
    'Team Name': 't3-tribe',
    'Team Leader': 'Nagaraj Pandith',
    Category: 'Finance',
    Participants: ['Swasthik Shetty'],
  },
  F05: {
    'College Name': 'St Joseph Engineering College',
    'Team Name': 'Xtension',
    'Team Leader': 'Rayan Dsilva',
    Category: 'Finance',
    Participants: ['Ovin D Almeida', 'Glenn Aston'],
  },
  F06: {
    'College Name': 'Sri Krishna College of Engineering and Technology (SKCET), Coimbatore',
    'Team Name': 'Debug Entity',
    'Team Leader': 'Vel Yogesh',
    Category: 'Finance',
    Participants: ['Bhuvaneshwari R', 'Sumalini G V'],
  },
  F07: {
    'College Name': 'Alvas Institute of Engineering and Technology, Mangalore, Karnataka',
    'Team Name': 'GOATS',
    'Team Leader': 'Koushik K',
    Category: 'Finance',
    Participants: ['Hardik Prabhu', 'Thejas Devadiga'],
  },
  F08: {
    'College Name': 'P A College of Engineering (PACOE), Mangalore',
    'Team Name': 'PACEMAKERS',
    'Team Leader': 'Mohammed Nouman',
    Category: 'Finance',
    Participants: ['Sheik Rifaz'],
  },
  F09: {
    'College Name': 'P A College of Engineering (PACOE), Mangalore',
    'Team Name': 'Straw hats',
    'Team Leader': 'Vaibhav Salian',
    Category: 'Finance',
    Participants: ['Ashley Dsouza', 'Mohammad Shaheer'],
  },
  F10: {
    'College Name': 'St Joseph Engineering College (SJEC), Mangaluru',
    'Team Name': 'SCEPTIX',
    'Team Leader': 'Vyasa M Nayak',
    Category: 'Finance',
    Participants: ['Devananda M', 'Alriya Treeza D Souza'],
  },
  E01: {
    'College Name': 'St. Joseph Engineering College, Mangalore, Karnataka',
    'Team Name': 'Jinsei',
    'Team Leader': 'Samwin Steve Pereira',
    Category: 'Energy and Sustainability',
    Participants: ['Charis Pinto', 'Joywin Bennis'],
  },
  E02: {
    'College Name': 'GM Institute of Technology (GMIT), Davangere',
    'Team Name': 'Carpool CREW',
    'Team Leader': 'Pranav V',
    Category: 'Energy and Sustainability',
    Participants: ['Pooja H P'],
  },
  E03: {
    'College Name': 'Srinivas University (SU), Mangaluru',
    'Team Name': 'GOLDEN-DAWN',
    'Team Leader': 'Amogh Rao',
    Category: 'Energy and Sustainability',
    Participants: ['B P Shashank', 'Tejas Pujari'],
  },
  E04: {
    'College Name': 'St Joseph Engineering College (SJEC), Mangaluru',
    'Team Name': 'The Tech Tribe',
    'Team Leader': 'Aditya Shriyan',
    Category: 'Energy and Sustainability',
    Participants: ['Sara Abdul', 'Sanmitha Shetty'],
  },
  E05: {
    'College Name': 'St. Joseph Engineering College, Mangalore, Karnataka',
    'Team Name': 'Soul Celestia',
    'Team Leader': 'Ralweena Rishal Lobo',
    Category: 'Energy and Sustainability',
    Participants: ['Joyline Rencita'],
  },
  E06: {
    'College Name': 'St Joseph Engineering College (SJEC), Mangaluru',
    'Team Name': 'wavy',
    'Team Leader': 'Adwaith Sajeev C',
    Category: 'Energy and Sustainability',
    Participants: ['Abhinav C Yadav', 'Ciana Rodrigues'],
  },
  E07: {
    'College Name': 'St Joseph Engineering College (SJEC), Mangaluru',
    'Team Name': 'Team Cypher',
    'Team Leader': 'Uthpal Suvarna',
    Category: 'Energy and Sustainability',
    Participants: ['Mohammad  Afeef', 'Thejas B Shetty'],
  },
  E08: {
    'College Name': 'St. Joseph Engineering College, Vamanjoor',
    'Team Name': 'Data Pirates',
    'Team Leader': 'Maria Viola',
    Category: 'Energy and Sustainability',
    Participants: ['Navyashree Salyan'],
  },
  E09: {
    'College Name': 'St. Joseph Engineering College, Vamanjoor',
    'Team Name': 'Team 404',
    'Team Leader': 'Bharath K',
    Category: 'Energy and Sustainability',
    Participants: ['Dhruva ', 'Ayush Maheshwari'],
  },
  E10: {
    'College Name': 'St. Joseph Engineering College, Vamanjoor',
    'Team Name': 'Peppermint plasters',
    'Team Leader': 'Lawrence Dsouza',
    Category: 'Energy and Sustainability',
    Participants: ['Deric Jojo', 'Joshua Quinthino Albuquerque'],
  },
  E11: {
    'College Name': 'Sri Eshwar College of Engineering (SECE), Tamil Nadu',
    'Team Name': 'Coding Puyal',
    'Team Leader': 'Nithinn Manickam',
    Category: 'Energy and Sustainability',
    Participants: ['Naveen', 'Madhu Mohan'],
  },
  E12: {
    'College Name': 'Kristu Jayanti College (KJC), Bangalore',
    'Team Name': 'Infinity coders',
    'Team Leader': 'Prajwal kumar',
    Category: 'Energy and Sustainability',
    Participants: ['Hithesh B', 'Raghav S'],
  },
  E13: {
    'College Name': 'St Joseph Engineering College (SJEC), Mangaluru',
    'Team Name': 'Fledge',
    'Team Leader': 'Siya Viju',
    Category: 'Energy and Sustainability',
    Participants: ['Vikhyath DK'],
  },
  E14: {
    'College Name': 'St Joseph Engineering College (SJEC), Mangaluru',
    'Team Name': 'Team-Alpha',
    'Team Leader': 'Swathi Rai',
    Category: 'Energy and Sustainability',
    Participants: ['Sonal Monis'],
  },
};
